// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxPHDNo0UYl9to2mu3TXAWHqAutQk2qXk',
    appId: '1:419872830898:web:5a2e040ea3efed63e660ab',
    messagingSenderId: '419872830898',
    projectId: 'fintenssapp',
    authDomain: 'fintenssapp.firebaseapp.com',
    storageBucket: 'fintenssapp.firebasestorage.app',
    measurementId: 'G-S2WYWLHL8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNZwrCCQ5bOOa2uMTCvraGLyFZK3kBNM',
    appId: '1:419872830898:android:387999f7cc25f3a6e660ab',
    messagingSenderId: '419872830898',
    projectId: 'fintenssapp',
    storageBucket: 'fintenssapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC703lPeEVH_ex6YKRwyDvxT5zIfFVAb-s',
    appId: '1:419872830898:ios:518dd046412c77eae660ab',
    messagingSenderId: '419872830898',
    projectId: 'fintenssapp',
    storageBucket: 'fintenssapp.firebasestorage.app',
    iosClientId: '419872830898-rjtuglabhigg8n4tmn2dtp1hirgi4b9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC703lPeEVH_ex6YKRwyDvxT5zIfFVAb-s',
    appId: '1:419872830898:ios:518dd046412c77eae660ab',
    messagingSenderId: '419872830898',
    projectId: 'fintenssapp',
    storageBucket: 'fintenssapp.firebasestorage.app',
    iosClientId: '419872830898-rjtuglabhigg8n4tmn2dtp1hirgi4b9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxPHDNo0UYl9to2mu3TXAWHqAutQk2qXk',
    appId: '1:419872830898:web:a1e07b2f40ac6177e660ab',
    messagingSenderId: '419872830898',
    projectId: 'fintenssapp',
    authDomain: 'fintenssapp.firebaseapp.com',
    storageBucket: 'fintenssapp.firebasestorage.app',
    measurementId: 'G-X6W2PN4HNR',
  );

}